### ISSUE TITLE
Local vs Global Orientation

### ISSUE THREAD

**Issue by xudh777** [abhi1kumar/DEVIANT#26]
I'm very sorry, but I have come across another place that I haven't quite understood and would like to ask for advice
The kitti dataset is annotated with alpha, Why obtain alpha through ry conversion.  And I found through testing that the converted alpha and the annotated alpha are not exactly the same. I really don't understand why everyone is doing this in engineering. 
Hope to receive guidance, thank you very much
![微信截图_20240112173437](https://github.com/abhi1kumar/DEVIANT/assets/52651891/7f4c6e2f-9c66-4945-856b-890153a36481)

**Comment by abhi1kumar** [comment]
Hi @xudh1991 
Thank you for your interest in DEVIANT again.

> Why obtain `alpha` through `ry` conversion.

To the best of my knowledge, the idea of regressing local orientation (`alpha`) instead of yaw / global orientation (`ry`) is from [3D Bounding Box Estimation Using Deep Learning and Geometry, Mousavian et al., CVPR 2017](https://arxiv.org/pdf/1612.00496.pdf) paper. Consider Fig. 4 of the above paper, which illustrates the motivation for regressing local over global orientation from the example of a car moving on a highway:

![Screenshot from 2024-01-18 14-10-15](https://github.com/abhi1kumar/DEVIANT/assets/43099708/d13ee17d-520c-4b46-b3d0-dfd6b0a0b89f)

The cropped car rotates as it moves away in the frontal view with the same yaw. This rotation creates issues for the frontal view detectors since now the detector has to output the same yaw even though the input images differ. Using local orientation alleviates this problem since the network now regresses different local orientations for these images, and one later converts local to global orientation.

**Comment by xudh777** [comment]
Thank you very much for your answer, it has been very helpful to me
