### ISSUE TITLE
能提供转换后的waymo数据集吗

### ISSUE THREAD

**Issue by wenjun1031** [abhi1kumar/DEVIANT#7]

**Comment by abhi1kumar** [comment]
Hi @wenjun1031,
Thank you for showing interest in DEVIANT. I used [Google translate](https://translate.google.com/?sl=auto&tl=en&text=%E8%83%BD%E6%8F%90%E4%BE%9B%E8%BD%AC%E6%8D%A2%E5%90%8E%E7%9A%84waymo%E6%95%B0%E6%8D%AE%E9%9B%86%E5%90%97&op=translate) to convert your question from Mandarin to English. Your question is copy of #5 . Please see [this answer](https://github.com/abhi1kumar/DEVIANT/issues/5#issuecomment-1450808230).

We release the converted `calib` and `label` subfolders of the waymo training and validation split at this[ drive link](https://drive.google.com/file/d/1Yzs3gZWsdvI0IX_ZjeiI5Y0XmrFutfFz/view?usp=sharing). 

You should follow these [instructions](https://github.com/abhi1kumar/DEVIANT/blob/main/data/data_setup_README.md#waymo) to get the converted waymo images. I can not release the converted waymo images because of the licensing issues and the huge size of the waymo dataset.

**Comment by Lyric0620** [comment]
@wenjun1031 请问你尝试转换过吗

**Comment by abhi1kumar** [comment]
Yes, I converted Waymo images to KITTI format with the released script.
