### ISSUE TITLE
Waymo Dataset Training Epochs

### ISSUE THREAD

**Issue by Lyric0620** [abhi1kumar/DEVIANT#9]
I'm trying to train deviant on waymo, and I read 1051.yaml. Is it ok to train 30 epochs on waymo? Or is it just a pretrained model config, and I should train more epochs.

**Comment by abhi1kumar** [comment]
Hi @Yutong-gannis 
Thank you for your interest in DEVIANT. 

> Is it ok to train 30 epochs on waymo? 

Yes, training for 30 epochs should be fine since Waymo is a huge dataset. We also trained our Waymo model for 30 epochs. 

Other paper such as [CaDDN](https://arxiv.org/pdf/2103.01100.pdf) train Waymo model for **10** epochs. See their Section 4 Training and Inference Details.

Also, please consider starring our repo and close your older issues.

**Comment by Lyric0620** [comment]
OK, thanks
